// Image object should be:
// {
//   images: [
//     {img: "https://s3.cucoarts.com/galery/zackrdz1"},
//     {img: "https://s3.cucoarts.com/galery/zackrdz2"},
//     {img: "https://s3.cucoarts.com/galery/zackrdz3"},
//     {img: "https://s3.cucoarts.com/galery/zackrdz4"},
//   ],
//   title: "Camera",
//   artistName: '',
//   description: '',
//   artistId: '',
//   artistImgId: 'zackrdz',
// },
const images = [
  {
    img: "https://cucoarts-image-assets.s3.us-east-2.amazonaws.com/galery/zackrdz3.JPG",
    title: "Breakfast",
    artistName: "",
  },
  {
    img: "https://cucoarts-image-assets.s3.us-east-2.amazonaws.com/galery/zackrdz4.JPG",
    title: "Burger",
    artistName: "",
  },
  {
    img: "https://cucoarts-image-assets.s3.us-east-2.amazonaws.com/galery/zackrdz5.JPG",
    title: "Burger",
    artistName: "",
  },
];
const texts = {
  t1: "Galería de Ideas",
  t2: "Encuentra obras de arte en diferentes estilos creadas por artistas profesionales alrededor del mundo.",
};
const fullGalery = [
  { img: "zackrdz1.JPG" },
  { img: "zackrdz2.JPG" },
  { img: "zackrdz3.JPG" },
  { img: "zackrdz4.JPG" },
  { img: "zackrdz5.JPG" },
  { img: "zackrdz1.JPG" },
  { img: "aarongarza1.JPG" },
  { img: "aarongarza2.JPG" },
  { img: "aarongarza3.JPG" },
  { img: "aarongarza4.JPG" },
  { img: "adan1.JPG" },
  { img: "alemirette1.JPG" },
  { img: "alemirette2.JPG" },
  { img: "alsahir1.JPG" },
  { img: "alsahir2.JPG" },
  { img: "alsahir3.JPG" },
  { img: "alsahir4.JPG" },
  { img: "anahid1.JPG" },
  { img: "anahid2.JPG" },
  { img: "anahid3.JPG" },
  { img: "anahid4.JPG" },
  { img: "andy1.JPG" },
  { img: "andy2.JPG" },
  { img: "andy3.JPG" },
  { img: "angelrmzv1.JPG" },
  { img: "angelrmzv2.JPG" },
  { img: "artby1.JPG" },
  { img: "aserodriguez.JPG" },
  { img: "aserodriguez2.JPG" },
  { img: "azhlynirvana1.JPG" },
  { img: "azhlynirvana2.JPG" },
  { img: "azhlynirvana3.JPG" },
  { img: "azhlynirvana4.JPG" },
  { img: "azhlynirvana5.JPG" },
  { img: "bacalao1.JPG" },
  { img: "bacalao2.JPG" },
  { img: "bacalao3.JPG" },
  { img: "bacalao4.JPG" },
  { img: "bacalao5.JPG" },
  { img: "bacalao6.jpg" },
  { img: "bacalao7.jpg" },
  { img: "banger1.JPG" },
  { img: "belindasalazar.JPG" },
  { img: "belindasalazar2.jpg" },
  { img: "belindasalazar3.jpg" },
  { img: "belindasalazar4.jpg" },
  { img: "belindasalazar5.jpg" },
  { img: "beohake.JPG" },
  { img: "beohake2.JPG" },
  { img: "beohake3.JPG" },
  { img: "beohake4.JPG" },
  { img: "beohake5.JPG" },
  { img: "beohake6.JPG" },
  { img: "bpvinalay1.JPG" },
  { img: "bpvinalay2.JPG" },
  { img: "bpvinalay3.JPG" },
  { img: "bpvinalay4.JPG" },
  { img: "bpvinalay5.JPG" },
  { img: "bpvinalay6.JPG" },
  { img: "bpvinalay7.JPG" },
  { img: "buffon92 1.JPG" },
  { img: "buffon92 2.JPG" },
  { img: "carrobledo1.JPG" },
  { img: "carrobledo2.JPG" },
  { img: "carrobledo3.JPG" },
  { img: "chanate1.JPG" },
  { img: "chanate2.JPG" },
  { img: "chanate3.JPG" },
  { img: "chanate4.JPG" },
  { img: "chanate5.JPG" },
  { img: "chanate6.JPG" },
  { img: "chanate7.JPG" },
  { img: "crip1.JPG" },
  { img: "dahiloart1.JPG" },
  { img: "dahiloart2.JPG" },
  { img: "dahiloart3.JPG" },
  { img: "daphne1.JPG" },
  { img: "daphne2.JPG" },
  { img: "dario1.JPG" },
  { img: "dario2.JPG" },
  { img: "dario3.JPG" },
  { img: "dazer1.JPG" },
  { img: "dazer10.JPG" },
  { img: "dazer11.JPG" },
  { img: "dazer12.JPG" },
  { img: "dazer2.JPG" },
  { img: "dazer3.JPG" },
  { img: "dazer4.JPG" },
  { img: "dazer5.JPG" },
  { img: "dazer6.JPG" },
  { img: "dazer7.JPG" },
  { img: "dazer8.JPG" },
  { img: "dazer9.JPG" },
  { img: "eder1.JPG" },
  { img: "eder2.JPG" },
  { img: "eder3.JPG" },
  { img: "eder4.JPG" },
  { img: "eliezer1.JPG" },
  { img: "eliezer2.JPG" },
  { img: "eliezer3.JPG" },
  { img: "eliezer4.JPG" },
  { img: "eskor1.JPG" },
  { img: "eskor2.JPG" },
  { img: "eskor3.JPG" },
  { img: "gerarobledo1.JPG" },
  { img: "gerarobledo2.JPG" },
  { img: "gerarobledo3.JPG" },
  { img: "gerarobledo4.JPG" },
  { img: "greometria.JPG" },
  { img: "guillen1.JPG" },
  { img: "guillen2.JPG" },
  { img: "guillen3.JPG" },
  { img: "guillen4.JPG" },
  { img: "guillen5.JPG" },
  { img: "guillen6.JPG" },
  { img: "ivanov1.JPG" },
  { img: "ivanov2.JPG" },
  { img: "ivanov3.JPG" },
  { img: "ivanov4.JPG" },
  { img: "miguel1.JPG" },
  { img: "miguel2.JPG" },
  { img: "mizael1.JPG" },
  { img: "mizael2.JPG" },
  { img: "mizael3.JPG" },
  { img: "mizael4.JPG" },
  { img: "mizael5.JPG" },
  { img: "mizael6.JPG" },
  { img: "mizael7.JPG" },
  { img: "mizael8.JPG" },
  { img: "mizael9.JPG" },
  { img: "narval1.JPG" },
  { img: "narval2.JPG" },
  { img: "narval3.JPG" },
  { img: "narval4.JPG" },
  { img: "oliinthespace.JPG" },
  { img: "oliinthespace2.JPG" },
  { img: "oliinthespace3.JPG" },
  { img: "oliinthespace4.jpg" },
  { img: "pablozeta1.JPG" },
  { img: "patohdz1.JPG" },
  { img: "piero1.JPG" },
  { img: "pront1.JPG" },
  { img: "pront2.JPG" },
  { img: "pront3.JPG" },
  { img: "pront4.JPG" },
  { img: "pura1.JPG" },
  { img: "pura2.JPG" },
  { img: "pura3.JPG" },
  { img: "pura4.JPG" },
  { img: "pura5.JPG" },
  { img: "raul1.JPG" },
  { img: "raul2.JPG" },
  { img: "raul3.JPG" },
  { img: "sad1.JPG" },
  { img: "sad2.JPG" },
  { img: "sad3.JPG" },
  { img: "silvestre3.jpg" },
  { img: "silvestremadera.JPG" },
  { img: "silvestremadera2.JPG" },
  { img: "snap1.JPG" },
  { img: "snap2.JPG" },
  { img: "tadeo1.JPG" },
  { img: "tadeo2.JPG" },
  { img: "tadeo3.JPG" },
  { img: "tadeo4.JPG" },
  { img: "tadeo5.JPG" },
  { img: "tadeo6.JPG" },
  { img: "tadeo7.JPG" },
  { img: "tateria1.JPG" },
  { img: "tateria11.JPG" },
  { img: "tateria2.JPG" },
  { img: "tateria3.JPG" },
  { img: "tateria4.JPG" },
  { img: "tateria5.JPG" },
  { img: "zackrdz1.JPG" },
  { img: "zackrdz2.JPG" },
  { img: "zackrdz3.JPG" },
  { img: "zackrdz4.JPG" },
  { img: "zackrdz5.JPG" },
  { img: "zackrdz6.JPG" },
];
export { images, texts, fullGalery };
