const images = [
  {
    img: "https://cucoarts-image-assets.s3.us-east-2.amazonaws.com/portfolio/Producci%C3%B3n/comercial+taller+gemma+oleos.jpg",
    title: "Produccion",
  },
  {
    img: "https://cucoarts-image-assets.s3.us-east-2.amazonaws.com/portfolio/Producci%C3%B3n/expo+virtual+asart+4.jpg",
    title: "Produccion",
  },
  {
    img: "https://cucoarts-image-assets.s3.us-east-2.amazonaws.com/portfolio/Producci%C3%B3n/video+podcast+ancestros+3.JPG",
    title: "Produccion",
  },
];

const texts = {
  t1: "Portafolio",
  t2: "Es una muestra de nuestra experiencia en producciones de eventos, artísticas o comerciales. Seguimos la filosofía del Colectivo: beneficio mútuo.",
};

const artHunting = [
  { img: "Arturo Lara para Ivan Lopez.png" },
  { img: "Camino de venta en imagenes-03.png" },
  { img: "Cliente contento 1.jpg" },
  { img: "Cliente contento 10.JPG" },
  { img: "Cliente contento 2.JPG" },
  { img: "Cliente contento 4.JPG" },
  { img: "Cliente contento 5.JPG" },
  { img: "Cliente contento 6.JPG" },
  { img: "Cliente contento 7.JPG" },
  { img: "Cliente contento 8.jpg" },
  { img: "Cliente contento 9.JPG" },
  { img: "Experiencia Mariam-01.png" },
  { img: "Intercambio ASART 1.JPG" },
  { img: "Intercambio ASART 2.JPG" },
  { img: "Intercambio ASART 3.JPG" },
  { img: "Intercambio ASART 4.JPG" },
  { img: "Intercambio ASART 5.JPG" },
  { img: "Intercambio ASART 6.JPG" },
  { img: "Obra para cliente 1.JPG" },
  { img: "Obra para cliente 2.JPG" },
  { img: "Obra para cliente 3.JPG" },
  { img: "Obra para cliente 4.png" },
  { img: "artista con obra para cliente 1.JPG" },
  { img: "cliente contento 3.JPG" },
];

const murals = [
  {img:"Jaaska Mural Cumbres.JPG"},
  {img:"Jaaska Nuevo CITADEL Colaborativo.JPG"},
  {img:"Jaaska Nuevo Sur Mural Colaborativo.jpg"},
  {img:"Jaaska Via Cordillera.jpg"},
  {img:"Josafk Via Cordillera.jpg"},
  {img:"Silvestre Madera GrillTeam centro.JPG"},
];

const events = [
  {img:"evento citadel 1.jpg"},
  {img:"evento citadel 2.jpg"},
  {img:"taller cumbres 1.JPG"},
  {img:"taller cumbres 2.JPG"},
  {img:"taller cumbres 3.JPG"},
  {img:"taller cumbres 4.JPG"},
  {img:"taller cumbres 5.JPG"},
  {img:"taller eliezer citadel.JPG"},
  {img:"taller lula rdz Centro Cuauhtemoc.JPG"},
]

const production = [
  {img:"DSC00195.JPG"},
  {img:"DSC00997.JPG"},
  {img:"DSC01298.JPG"},
  {img:"GLOBAL EXPO VIRTUAL 2020_Moment.jpg"},
  {img:"Logo ASART.png"},
  {img:"Vivisecciones mutuas-01.png"},
  {img:"comercial angeles falcon libro.jpg"},
  {img:"comercial laika 1.JPG"},
  {img:"comercial laika 2.JPG"},
  {img:"comercial laika 3.jpg"},
  {img:"comercial taller gemma oleos.jpg"},
  {img:"documental ancestros 1.JPG"},
  {img:"documental ancestros 2.JPG"},
  {img:"evento javier carrera.JPG"},
  {img:"expo virtual asart 1.jpg"},
  {img:"expo virtual asart 2.jpg"},
  {img:"expo virtual asart 3.jpg"},
  {img:"expo virtual asart 4.jpg"},
  {img:"expo virtual asart 5.jpg"},
  {img:"fb ancestros.JPG"},
  {img:"fb asart.JPG"},
  {img:"fb salamanca 2.JPG"},
  {img:"fb salamanca 3.JPG"},
  {img:"fb salamanca.JPG"},
  {img:"giveaway 1.JPG"},
  {img:"giveaway 2.png"},
  {img:"giveaway 3.JPG"},
  {img:"giveaway 4.JPG"},
  {img:"giveaway 5.png"},
  {img:"giveaway 6.png"},
  {img:"giveaway 7.png"},
  {img:"intercambio ASART.jpg"},
  {img:"taller pequenos tlacuilos.jpg"},
  {img:"video musical ancestros 1.JPG"},
  {img:"video musical somos mexico 2.JPG"},
  {img:"video musical somos mexico.jpg"},
  {img:"video musical vivan las mujeres 1.JPG"},
  {img:"video podcast ancestros 1.JPG"},
  {img:"video podcast ancestros 2.jpg"},
  {img:"video podcast ancestros 3.JPG"},
  {img:"video podcast ancestros 4.jpg"},
  {img:"video podcast ancestros 6.jpg"},
  {img:"video podcast edgar cantu.jpg"},
  {img:"yt ancestros.JPG"},
  {img:"yt comunidad zohar.JPG"},
  {img:"yt tlacuilos.JPG"},
]

export { images, texts, artHunting, murals, events, production };
